from __future__ import annotations

import sys
from pathlib import Path

import click

from .config import load_config
from .reducer import simple_reducer
from .runner import run_cases
from .llm_runner import run_llm_cases
from .mcp_server import serve_mcp


@click.group()
def cli():
    pass


@cli.command()
@click.option("--config", "config_path", type=click.Path(exists=False, dir_okay=False), default="config.yaml")
@click.option("--cases", type=int, default=None, help="Override number of cases")
@click.option("--seed", type=int, default=None, help="Override RNG seed")
@click.option("--case-offset", type=int, default=0, help="Start case index")
def run(config_path: str, cases: int | None, seed: int | None, case_offset: int):
    cfg = load_config(config_path if config_path and Path(config_path).exists() else None)
    failures = run_cases(cfg, cases=cases, seed=seed, case_offset=case_offset)
    click.echo(f"Completed with {failures} mismatches.")
    sys.exit(1 if failures else 0)


@cli.command()
@click.option("--config", "config_path", type=click.Path(exists=False, dir_okay=False), default="config.yaml")
@click.option("--input", "input_sql", type=click.Path(exists=True, dir_okay=False), required=True)
@click.option("--seed", type=int, default=0, help="Seed for deterministic reduction order")
def reduce(config_path: str, input_sql: str, seed: int):
    _ = load_config(config_path if config_path and Path(config_path).exists() else None)

    def test_fn(sql: str) -> bool:
        # Placeholder: user should implement calling the harness on the fixed schema+query
        # For now, always return False (no mismatch) to avoid loops
        return False

    original = Path(input_sql).read_text(encoding="utf-8")
    reduced = simple_reducer(original, rng_seed=seed, test_fn=test_fn)
    Path("reduced.sql").write_text(reduced, encoding="utf-8")
    click.echo("Wrote reduced.sql")


@cli.command("llm-run")
@click.option("--config", "config_path", type=click.Path(exists=False, dir_okay=False), default="config.yaml")
@click.option("--cases", type=int, default=None, help="Override number of schema cases")
@click.option("--seed", type=int, default=None, help="Override RNG seed")
@click.option("--queries-per-case", type=int, default=None, help="Queries per schema generated by LLM")
@click.option("--topics", type=str, default="", help="Comma-separated topics: joins,aggregates,window,subqueries,setops,casts")
def llm_run(config_path: str, cases: int | None, seed: int | None, queries_per_case: int | None, topics: str):
    cfg = load_config(config_path if config_path and Path(config_path).exists() else None)
    topic_list = [t.strip() for t in topics.split(",") if t.strip()] if topics else None
    failures = run_llm_cases(cfg, cases=cases, seed=seed, topics=topic_list, queries_per_case=queries_per_case)
    click.echo(f"Completed with {failures} mismatches.")
    sys.exit(1 if failures else 0)


@cli.command("mcp-server")
@click.option("--config", "config_path", type=click.Path(exists=False, dir_okay=False), default="config.yaml")
def mcp_server(config_path: str):
    # Start MCP server over stdio; your MCP-enabled client will launch this
    serve_mcp(config_path if config_path and Path(config_path).exists() else None)


def main():
    cli(prog_name="ydiff")


if __name__ == "__main__":
    main()
